theme: jekyll-theme-modernist
jekyll_admin:
  hidden_links:
    - posts
  homepage: "pages"
plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
